//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABMANAGE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> State { get; set; }
        public int Shift { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual User User { get; set; }
    }
}
