//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABMANAGE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Duty = new HashSet<Duty>();
            this.Equipment = new HashSet<Equipment>();
            this.Leave = new HashSet<Leave>();
            this.Notice = new HashSet<Notice>();
            this.Summary = new HashSet<Summary>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Real_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public int U_Role { get; set; }
        public string Image { get; set; }
        public string Motto { get; set; }
        public Nullable<bool> IsExamine { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Register_Time { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public bool IsNotice { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<Duty> Duty { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<Leave> Leave { get; set; }
        public virtual ICollection<Notice> Notice { get; set; }
        public virtual Role Role { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Summary> Summary { get; set; }
    }
}
